runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static
  secure: always

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /.*
  script: main.app
  secure: always
